name: main
on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: actions/cache@v3
      if: needs.files-changed.outputs.backend == 'true'
      with:
        path: ~/.cache/pre-commit
        key: cache-epoch-1|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run: pip install pre-commit
    - run: pre-commit run --all-files --show-diff-on-failure
